---
version: '3'

services:
  ### ARVADOS-SERVER
  arvados-server:
    image: nmarvie/server
    build:
      context: .
      dockerfile: Dockerfile.goapp
      args:
        APP_DIR: cmd
        APP_NAME: arvados-server
  ### ARVADOS-CLIENT
  arvados-client:
    image: nmarvie/client
    build:
      context: .
      dockerfile: Dockerfile.goapp
      args:
        APP_DIR: cmd
        APP_NAME: arvados-client
  ### API
  # The API image can be build and run standalone as a rails app,
  api:
    image: nmarvie/api
    build:
      context: .
      dockerfile: Dockerfile.rails
      args:
        APP_DIR: services
        APP_NAME: api
        PORT: 8004
        GEM_HOME: /cache/gem
        NPM_CONFIG_PREFIX: /cache/npm
        PIPCACHE: /cache/pip
  ### WORKBENCH
  workbench:
    image: nmarvie/workbench
    build:
      context: .
      dockerfile: Dockerfile.rails
      args:
        APP_DIR: apps
        APP_NAME: workbench
        PORT: 9002
        GEM_HOME: /cache/gem
        NPM_CONFIG_PREFIX: /cache/npm
        PIPCACHE: /cache/pip
  ### GIT-HTTPD
  git-httpd:
    image: nmarvie/git-httpd
    build:
      context: .
      dockerfile: Dockerfile.goapp
      args:
        APP_DIR: services
        APP_NAME: arv-git-httpd
  crunch-dispatch-local:
    # FIXME! Not sure if it needs a whole dockerd or a docker client
    # https://stackoverflow.com/questions/27879713/is-it-ok-to-run-docker-from-inside-docker
    image: nmarvie/crunch-dispatch-local
    build:
      context: .
      dockerfile: Dockerfile.goapp.crunch-dispatch-local
      args:
        APP_DIR: services
        APP_NAME: crunch-dispatch-local
  # crunch-dispatch-slurm:
  # crunch-run:
  # crunchstat:
  # dockercleaner:
  # fuse:
  health:
    image: nmarvie/health
    build:
      context: .
      dockerfile: Dockerfile.goapp
      args:
        APP_DIR: services
        APP_NAME: health
  keep-balance:
    image: nmarvie/keep-balance
    build:
      context: .
      dockerfile: Dockerfile.goapp
      args:
        APP_DIR: services
        APP_NAME: keep-balance
  keepproxy:
    image: nmarvie/keepproxy
    build:
      context: .
      dockerfile: Dockerfile.goapp
      args:
        APP_DIR: services
        APP_NAME: keepproxy
  keep-web:
    image: nmarvie/keep-web
    build:
      context: .
      dockerfile: Dockerfile.goapp
      args:
        APP_DIR: services
        APP_NAME: keep-web
  keepstore:
    image: nmarvie/keepstore
    build:
      context: .
      dockerfile: Dockerfile.goapp
      args:
        APP_DIR: services
        APP_NAME: keepstore
