---
# arvados-api-server
# arvados-composer
# arvados-dispatch-cloud
# arvados-docker-cleaner
# arvados-git-httpd
# arvados-health
# arvados-node-manager
# arvados-sync-groups
# arvados-workbench
# arvados-workbench2

# According to arvbox, instances are
# api
# keep-web
# workbench2
# controller
# keepstore0
# keepstore1
# workbench
# sso
# websockets
# arv-git-httpd
# keepproxy
# composer
# docker
# crunch-dispatch

version: '3'

services:
  ### DATABASE
  database:
    container_name: database
    image: 'postgres:11-alpine'
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ${PG_DATA}:/var/lib/postgresql/data
      - ${PWD}/scripts/postgresql:/docker-entrypoint-initdb.d
      - ${PWD}/configs/ssl/server.crt:/var/lib/postgresql/server.crt:ro
      - ${PWD}/configs/ssl/server.key:/var/lib/postgresql/server.key:ro
    # yamllint disable-line rule:line-length
    command: postgres -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    # yamllint enable-line rule:line-length
    environment:
      POSTGRES_PASSWORD: ${PG_ADMIN_PASSWORD}
  ### CONTROLLER
  controller:
    container_name: controller
    image: nmarvie/server
    ports:
      - 8003:8003
    restart: always
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
    command: controller
    depends_on:
      - database
  ### WEBSOCKETS
  # websocket:
  #   container_name: websocket
  #   image: nmarvie/server
  #   ports:
  #     - 8005:8005
  #   restart: always
  #   volumes:
  #     - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
  #   command: ws
  ### API
  api:
    container_name: api
    image: nmarvie/api
    command: /scripts/ruby/app_start 8004
    tty: true   # Enables debugging capabilities when attached to this container.
    ports:
      - 8004:8004
    restart: always
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
      - ${PWD}/${ETC_ARVADOS}/arvados-api-database.yml:/etc/arvados/database.yml
      - ${PWD}/${HOST_GEMCACHE}:/cache/gem
      - ${PWD}/${HOST_NPMCACHE}:/cache/npm
      - ${ARVADOS_ROOT}:/usr/src/arvados
      - ${ARVBOX_FLAGS}:/arvados/flags
      - ${PWD}/scripts:/scripts
    environment:
      NPM_CONFIG_PREFIX: ${HOST_NPMCACHE}
      npm_config_cache_min: ${NPM_CACHE_MIN}
    links:
      - database
    depends_on:
      - database
      - controller
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - "8080:80"
      - "4443:443"
    volumes:
      - ${PWD}/${ETC_NGINX}:/etc/nginx/conf.d
      - ${PWD}/configs/ssl:/etc/nginx/ssl:ro
    depends_on:
      - controller
      - api
      - workbench
      - keep
  ### WORKBENCH
  workbench:
    container_name: workbench
    image: nmarvie/workbench
    command: /scripts/ruby/app_start 9000
    tty: true   # Enables debugging capabilities when attached to this container.
    ports:
      - 9000:9000
    restart: always
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
      - ${PWD}/${ETC_ARVADOS}/arvados-workbench-application.yml:/etc/arvados/application.yml
      # FIXME! This needs to be really used
      - ${PWD}/${HOST_GEMCACHE}:/cache/gem
      - ${PWD}/${HOST_PIPCACHE}:/cache.pip
      - ${PWD}/${HOST_NPMCACHE}:/cache/npm
      - ${ARVADOS_ROOT}:/usr/src/arvados
      - ${ARVBOX_FLAGS}:/arvados/flags
      - ${PWD}/scripts:/scripts
    environment:
      npm_config_cache: ${NPM_CACHE}
      npm_config_cache_min: ${NPM_CACHE_MIN}
    depends_on:
      - controller
      - api
  ### GIT-HTTPD
  git-httpd:
    container_name: git-httpd
    image: nmarvie/git-httpd
    ports:
      - 9001:9001
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
  crunch-dispatch-local:
    # https://stackoverflow.com/questions/27879713/is-it-ok-to-run-docker-from-inside-docker
    # TL;RL: no, it's not. you better run siblings
    image: nmarvie/crunch-dispatch-local
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
  # FIXME
  # crunch-dispatch-slurm:
  # crunch-run:
  # crunchstat:
  # dockercleaner:
  # fuse:
  health:
    container_name: health
    image: nmarvie/health
    volumes:
      - ${PWD}/${ARVADOS_ROOT}:/usr/src/arvados
  keep-balance:
    container_name: keep-balance
    image: nmarvie/keep-balance
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
  keep:
    container_name: keep
    image: nmarvie/keepproxy
    ports:
      - 25100:25100
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
  keep-web:
    container_name: keep-web
    image: nmarvie/keep-web
    ports:
      - 9003:9003
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
  keep0:
    container_name: keep0
    image: nmarvie/keepstore
    ports:
      - 25107:25107
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
      - ${KEEP0_DATA}:/var/lib/arvados/keep0
  keep1:
    container_name: keep1
    image: nmarvie/keepstore
    ports:
      - 25108:25108
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
      - ${KEEP1_DATA}:/var/lib/arvados/keep1
