---
version: '3'

services:
  ### DATABASE
  database:
    container_name: database
    image: 'postgres:11-alpine'
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ${PG_DATA}:/var/lib/postgresql/data
      - ${PWD}/scripts/postgresql:/docker-entrypoint-initdb.d
      - ${PWD}/configs/ssl/server.crt:/var/lib/postgresql/server.crt:ro
      - ${PWD}/configs/ssl/server.key:/var/lib/postgresql/server.key:ro
    # yamllint disable-line rule:line-length
    command: postgres -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    # yamllint enable-line rule:line-length
    environment:
      POSTGRES_PASSWORD: ${PG_ADMIN_PASSWORD}
  ### CONTROLLER
  controller:
    container_name: controller
    image: nmarvie/server
    # ports:
    #   - 8000:8003
    restart: always
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
    command: controller
    depends_on:
      - database
  ### WEBSOCKETS
  websocket:
    container_name: websocket
    image: nmarvie/server
    # ports:
    #   - 8002:8005
    restart: always
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
    command: ws
    depends_on:
      - api
      - controller
  ### API
  api:
    container_name: api
    image: nmarvie/api
    command: /scripts/ruby/app_start 8004
    tty: true   # Enables debugging capabilities when attached to this container.
    # ports:
    #   - 8004:8004
    restart: always
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
      - ${PWD}/${ETC_ARVADOS}/arvados-api-database.yml:/etc/arvados/database.yml
      - ${PWD}/${HOST_GEMCACHE}:/cache/gem
      - ${PWD}/${HOST_NPMCACHE}:/cache/npm
      - ${ARVADOS_ROOT}:/usr/src/arvados
      - ${ARVBOX_FLAGS}:/arvados/flags
      - ${PWD}/scripts:/scripts
    environment:
      NPM_CONFIG_PREFIX: /cache/npm
      npm_config_cache_min: ${NPM_CACHE_MIN}
    depends_on:
      - database
      - controller
  nginx:
    container_name: nginx
    networks:
      default:
        aliases:
          - ${CLUSTER}.${DOMAIN}
          - workbench.${CLUSTER}.${DOMAIN}
          - workbench2.${CLUSTER}.${DOMAIN}
          - collections.${CLUSTER}.${DOMAIN}
          - download.${CLUSTER}.${DOMAIN}
          - keep.${CLUSTER}.${DOMAIN}
          - webshell.${CLUSTER}.${DOMAIN}
          - ws.${CLUSTER}.${DOMAIN}
    image: nginx:stable-alpine
    restart: always
    ports:
      # Unused. Default
      # - "8080:80"
      # Controller
      - "8000:8000"
      # Websocket
      - "8002:8002"
      # Workbench
      - "8443:8443"
      # Keepweb
      - "9002:9002"
      # Keepproxy
      - "25101:25101"
    volumes:
      - ${PWD}/${ETC_NGINX}:/etc/nginx/conf.d
      - ${PWD}/configs/ssl:/etc/nginx/ssl:ro
    depends_on:
      - controller
      - api
      - workbench
      - keep
  ### WORKBENCH
  workbench:
    container_name: workbench
    image: nmarvie/workbench
    command: /scripts/ruby/app_start 8002
    tty: true   # Enables debugging capabilities when attached to this container.
    # ports:
    #   - 8443:8443
    restart: always
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
      - ${PWD}/${ETC_ARVADOS}/arvados-workbench-application.yml:/etc/arvados/application.yml
      # FIXME! This needs to be really used
      - ${PWD}/${HOST_GEMCACHE}:/cache/gem
      - ${PWD}/${HOST_PIPCACHE}:/cache.pip
      - ${PWD}/${HOST_NPMCACHE}:/cache/npm
      - ${ARVADOS_ROOT}:/usr/src/arvados
      - ${ARVBOX_FLAGS}:/arvados/flags
      - ${PWD}/scripts:/scripts
    environment:
      npm_config_cache: /cache/npm
      npm_config_cache_min: ${NPM_CACHE_MIN}
    depends_on:
      - controller
      - api
  ### GIT-HTTPD
  # git-httpd:
  #   container_name: git-httpd
  #   image: nmarvie/git-httpd
  #   ports:
  #     - 9001:9001
  #   volumes:
  #     - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
  crunch-dispatch-local:
    container_name: dispatcher
    # https://stackoverflow.com/questions/27879713/is-it-ok-to-run-docker-from-inside-docker
    # TL;DR: no, it's not. you better run siblings
    image: nmarvie/crunch-dispatch-local
    # command: '-poll-interval=1 -crunch-run-command=/usr/local/bin/crunch-run'
    command: '-poll-interval=1'
    environment:
      ARVADOS_HOST: api
      ARVADOS_API_TOKEN: system_root_token
      ARVADOS_API_HOST_INSECURE: 1
    tty: true   # Enables debugging capabilities when attached to this container.
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
  # FIXME! If we want to use the slurm dispatcher
  # compute0:
  #   container_name: compute
  #   image: nmarvie/compute
  #   tty: true   # Enables debugging capabilities when attached to this container.
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /usr/bin/docker:/usr/bin/docker
  # health:
  #   container_name: health
  #   image: nmarvie/health
  #   volumes:
  #     - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
  # keep-balance:
  #   container_name: keep-balance
  #   image: nmarvie/keep-balance
  #   volumes:
  #     - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
  keep:
    container_name: keep
    image: nmarvie/keepproxy
    # ports:
    #   - 25101:25100
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
    depends_on:
      - controller
      - api
      - keep0
      - keep1
  keepweb:
    container_name: keepweb
    image: nmarvie/keep-web
    # ports:
    #   - 9002:9003
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
    depends_on:
      - controller
      - api
  keep0:
    container_name: keep0
    image: nmarvie/keepstore
    # ports:
    #   - 25107:25107
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
      - ${KEEP0_DATA}:/var/lib/arvados/keep0
  keep1:
    container_name: keep1
    image: nmarvie/keepstore
    # ports:
    #   - 25108:25108
    volumes:
      - ${PWD}/${ETC_ARVADOS}/arvados-config.yml:/etc/arvados/config.yml
      - ${KEEP1_DATA}:/var/lib/arvados/keep1
  shell:
    container_name: shell
    image: nmarvie/shell
    tty: true   # Enables debugging capabilities when attached to this container.
    # ports:
    #   - 2222:22
    volumes:
      - ${ARVADOS_ROOT}:/usr/src/arvados
      - ${PWD}/${HOST_GEMCACHE}:/cache/gem
      - ${PWD}/${HOST_NPMCACHE}:/cache/npm
      # FIXME! arvados-cwl-runner (and perhaps other tools need docker?)
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      NPM_CONFIG_PREFIX: /cache/npm
      npm_config_cache_min: ${NPM_CACHE_MIN}
