#!/bin/bash

# This script will prepare your env to run Arvie.
# It needs to create SSL certs for postgresql, or websocket won't communicate with it.
# Also, will populate arvados dir for the first time.

set -euo pipefail

echo "Generating the Postgresql SSL cert"
mkdir -p configs/ssl
openssl req -new -text -passout pass:abcd -subj /CN=localhost -out configs/ssl/server.req -keyout configs/ssl/privkey.pem
openssl rsa -in configs/ssl/privkey.pem -passin pass:abcd -out configs/ssl/server.key
openssl req -x509 -in configs/ssl/server.req -text -key configs/ssl/server.key -out configs/ssl/server.crt
chmod 600 configs/ssl/server.key
test $(uname -s) == Linux && sudo chown 70 configs/ssl/server.key

echo "Downloading Arvados"
git submodule update --init
git submodule update --checkout
