Clusters:
  vwxyz:
    SystemRootToken: system_root_token
    ManagementToken: management_token
    TLS:
      Insecure: true
    Services:
      RailsAPI:
        InternalURLs:
          "http://localhost:8004": {}
      Workbench1:
        ExternalURL: "https://workbench:443"
      Workbench2:
        ExternalURL: "https://workbench2:3002"
      Keepproxy:
        ExternalURL: "https://keep:25101"
        InternalURLs:
          "http://keep:25100": {}
      Keepstore:
        InternalURLs:
          "http://keep0:25107": {}
          "http://keep1:25108": {}
      Websocket:
        ExternalURL: "wss://ws:8002/websocket"
        InternalURLs:
          "http://ws:8005": {}
      GitSSH:
        ExternalURL: "ssh://git@127.0.0.1:"
      GitHTTP:
        InternalURLs:
          "http://localhost:9001/": {}
        ExternalURL: "https://127.0.0.1:9000/"
      WebDAV:
        InternalURLs:
          "http://localhost:9003/": {}
        ExternalURL: "https://127.0.0.1:9002/"
      WebDAVDownload:
        InternalURLs:
          "http://localhost:9003/": {}
        ExternalURL: "https://127.0.0.1:9002/"
        InternalURLs:
          "http://localhost:9003/": {}
      Composer:
        ExternalURL: "https://127.0.0.1:4200"
      Controller:
        ExternalURL: "https://127.0.0.1:8000"
        InternalURLs:
          "http://localhost:8003": {}
      RailsAPI:
        InternalURLs:
          "http://localhost:8004/": {}
    PostgreSQL:
      ConnectionPool: 32 # max concurrent connections per arvados server daemon
      Connection:
        # All parameters here are passed to the PG client library in a connection string;
        # see https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-PARAMKEYWORDS
        host: database
        user: arvados
        password: arvados
        dbname: arvados
        client_encoding: utf8
    API:
      RailsSessionSecretToken: rails_session_secret_token
    Collections:
      BlobSigningKey: blob_signing_key
      DefaultReplication: 1
      TrustAllContent: true
    Login:
      ProviderAppSecret: sso_app_secret
      ProviderAppID: arvados-server
    Users:
      NewUsersAreActive: true
      AutoAdminFirstUser: true
      AutoSetupNewUsers: true
      AutoSetupNewUsersWithVmUUID: vm_uuid
      AutoSetupNewUsersWithRepository: true
    Workbench:
      SecretKeyBase: workbench_secret_key_base
      ArvadosDocsite: http://127.0.0.1:8001/
    Git:
      GitCommand: /usr/share/gitolite3/gitolite-shell
      GitoliteHome: /var/lib/arvados/git
      Repositories: /var/lib/arvados/git/repositories
    Volumes:
      vwxyz-nyw5e-000000000000000:
        Driver: Directory
        DriverParameters:
          Root: /var/lib/arvados/keep0
        AccessViaHosts:
          "http://keep0:25107": {}
      vwxyz-nyw5e-111111111111111:
        Driver: Directory
        DriverParameters:
          Root: /var/lib/arvados/keep1
        AccessViaHosts:
          "http://keep1:25108": {}
