#!/bin/bash

set -euo pipefail

COMMAND=$(basename $0)

usage() {
  echo >&2
  echo >&2 "Deletes lingering Arvados files or all data ,if desired"
  echo >&2
  echo >&2 "Usage: arvie ${COMMAND} [-h|--help] [-a|--all]"
  echo >&2
  echo >&2 "${COMMAND} options:"
  echo >&2 "  -h, --help            Display this help and exit"
  echo >&2 "  -a, --all             Deletes all locally persisted data"
  echo >&2 "                        from HOST_DATA_DIR and HOST_CACHE_DIR"
  echo >&2
}

if [ "x${1:-}" = "x-h" -o "x${1:-}" = "x--help" ]; then
  usage
  exit 0
fi

source .env

# Clean stuff lingering around so we can reset everything
cd ${ARVADOS_ROOT} || exit 1

echo "FIXME! Removing PID files"
sudo rm -vf apps/workbench/tmp/pids/server.pid services/api/tmp/pids/server.pid

echo "FIXME! resetting db files, modified by api on startup"
git checkout -- apps/workbench/db/schema.rb services/api/db/structure.sql
cd ${BASE_DIR}

if [ "x${1:-}" = "x-a" -o "x${1:-}" = "x--all" ]; then
  echo "Removing all locally persisted data"
  sudo rm -rvf ${HOST_CACHE_DIR} ${HOST_DATA_DIR}
fi
