---
# This is the opentracing docker-compose.yml file,
# Is the one that will be used when invoking 'arvie trace'

version: '3.8'

services:
  nginx:
    image: opentracing/nginx-opentracing
    ports:
      # Opentracing
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      # This is for opentracing with jaeger
      # https://github.com/opentracing-contrib/nginx-opentracing/tree/master/example/trivial/jaeger
      - ${PWD}/configs/extras/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/configs/extras/jaeger-nginx-config.json:/etc/jaeger-config.json
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      default:
        aliases:
          - jaeger
    expose:
      - "9411"
      - "16686"
    ports:
      - "9411:9411"
      - "16686:16686"
