#!/bin/bash
# Check arvados/tools/arvbox/lib/arvbox/docker/api-setup.sh

PORT=$1

export GEM_HOME=/cache/gems
export NPM_CONFIG_PREFIX=/cache/npm

echo "Run bundle install if required"
bundle check || bundle install

echo "Try to create the database if /arvados/flags/api_database_setup does not exist"
if ! test -f /arvados/flags/api_database_setup ; then
  bundle exec rake db:setup && \
  # PGPASSWORD=arvados psql -v --username arvados --dbname arvados -f /usr/src/arvados/services/api/db/structure.sql
  touch /arvados/flags/api_database_setup
fi

echo "Run migrations to update/upgrade the database structure"
bundle exec rake db:migrate

# Tried to add this to the Dockerfile, but the npm assets need the /etc/arvados/config.yml file in place
echo "Building and precompiling assets"
RAILS_GROUPS=assets bundle exec rake npm:install && \
  bundle exec rake assets:precompile

bundle exec rails server -b 0.0.0.0 -p ${PORT}
