#!/bin/bash
# Check arvados/tools/arvbox/lib/arvbox/docker/api-setup.sh

PORT=$1

echo "Run bundle install if required"
bundle check || bundle install

echo "Try to create the database if /arvados/flags/api_database_setup does not exist"
if ! test -f /arvados/flags/api_database_setup ; then
  bundle exec rake db:setup && \
  # PGPASSWORD=arvados psql -v --username arvados --dbname arvados -f /usr/src/arvados/services/api/db/structure.sql
  touch /arvados/flags/api_database_setup
fi

echo "Run migrations to update/upgrade the database structure"
bundle exec rake db:migrate
bundle exec rails server -b 0.0.0.0 -p ${PORT}
