#!/bin/bash

# This script is used to build the gems cache for the ruby apps.
# It's run from the instances launched with the docker-compose-cache-builder.yml file

export GEM_HOME=/cache/gems
export NPM_CONFIG_PREFIX=/cache/npm

apt-get update && \
apt-get install --yes \
     --no-install-recommends \
     bundler \
     curl \
     g++ \
     gcc \
     git \
     libcurl4 \
     libcurl4-gnutls-dev \
     libpq-dev \
     libxml2 \
     libxml2-dev \
     make \
     npm \
     postgresql-client \
     python-dev \
     ruby-dev \
     zlib1g-dev

cd /usr/src/arvados
for GF in apps/workbench services/api; do
  cd ${GF}
  bundle install --retry=20
  cd -
done
